# Generated by Django 5.0.3 on 2025-05-05 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商店名称')),
                ('avatar', models.ImageField(upload_to='shop_avatars/', verbose_name='商店头像')),
                ('description', models.TextField(blank=True, verbose_name='商店简介')),
                ('real_name', models.CharField(max_length=100, verbose_name='注册人姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('id_front', models.ImageField(upload_to='id_cards/', verbose_name='身份证正面')),
                ('id_back', models.ImageField(upload_to='id_cards/', verbose_name='身份证反面')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否通过审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='商家用户')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('description', models.TextField(blank=True, verbose_name='商品简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.shop', verbose_name='所属商店')),
            ],
        ),
    ]
