# Generated by Django 5.0.3 on 2025-05-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='total_gold_coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
