# Generated by Django 5.0.3 on 2025-05-05 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('description', models.TextField(blank=True, verbose_name='商品简介')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='商品图片')),
                ('video', models.FileField(blank=True, null=True, upload_to='product_videos/', verbose_name='商品视频')),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='product_models/', verbose_name='3D模型文件')),
                ('tripo_task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tripo3D任务ID')),
                ('tripo_status', models.CharField(blank=True, default='未开始', max_length=50, null=True, verbose_name='3D生成状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.shop', verbose_name='所属商店')),
            ],
        ),
    ]
