# Generated by Django 5.0.3 on 2025-05-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_3d',
        ),
        migrations.AddField(
            model_name='product',
            name='tripo_3d_model',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/', verbose_name='3D模型'),
        ),
    ]
