# Generated by Django 5.0.3 on 2025-05-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_product_model_3d_product_tripo_3d_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='未分类', verbose_name='商品分类'),
        ),
    ]
