# Generated by Django 5.0.3 on 2025-05-11 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0002_customuser_gold_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', '待审核'), ('done', '已到账'), ('rejected', '已驳回')], default='waiting', max_length=10)),
                ('note', models.TextField(blank=True, help_text='备注或管理员填写的处理说明')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
