# Generated by Django 5.0.3 on 2025-05-11 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0003_goldrecharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldrecharge',
            name='note',
        ),
        migrations.AlterField(
            model_name='goldrecharge',
            name='status',
            field=models.CharField(choices=[('waiting', '待审核'), ('done', '已到账')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='goldrecharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
